# Generated by Django 5.0.3 on 2024-03-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('rated', models.CharField(max_length=10)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('ratings', models.JSONField()),
                ('metascore', models.IntegerField()),
                ('imdb_rating', models.FloatField()),
                ('imdb_votes', models.CharField(max_length=30)),
                ('imdb_id', models.CharField(max_length=20)),
                ('movie_type', models.CharField(max_length=20)),
                ('dvd_release', models.DateField()),
                ('box_office', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('response', models.BooleanField()),
            ],
        ),
    ]
